// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: spfresh.proto

package tipb

import (
	encoding_binary "encoding/binary"
	"fmt"
	"io"
	"math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"

	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SPFreshTruncateMode int32

const (
	SPFreshTruncateMode_TruncateError   SPFreshTruncateMode = 0
	SPFreshTruncateMode_TruncateIgnore  SPFreshTruncateMode = 1
	SPFreshTruncateMode_TruncateWarning SPFreshTruncateMode = 2
)

var SPFreshTruncateMode_name = map[int32]string{
	0: "TruncateError",
	1: "TruncateIgnore",
	2: "TruncateWarning",
}

var SPFreshTruncateMode_value = map[string]int32{
	"TruncateError":   0,
	"TruncateIgnore":  1,
	"TruncateWarning": 2,
}

func (x SPFreshTruncateMode) String() string {
	return proto.EnumName(SPFreshTruncateMode_name, int32(x))
}

func (SPFreshTruncateMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aabe6432836b2ba5, []int{0}
}

type SPFreshFilterExprColumnSource int32

const (
	SPFreshFilterExprColumnSource_Stored SPFreshFilterExprColumnSource = 0
	SPFreshFilterExprColumnSource_Handle SPFreshFilterExprColumnSource = 1
)

var SPFreshFilterExprColumnSource_name = map[int32]string{
	0: "Stored",
	1: "Handle",
}

var SPFreshFilterExprColumnSource_value = map[string]int32{
	"Stored": 0,
	"Handle": 1,
}

func (x SPFreshFilterExprColumnSource) String() string {
	return proto.EnumName(SPFreshFilterExprColumnSource_name, int32(x))
}

func (SPFreshFilterExprColumnSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aabe6432836b2ba5, []int{1}
}

type SPFreshTeardownRequest struct {
	KeyspaceId uint32 `protobuf:"varint,1,opt,name=keyspace_id,json=keyspaceId,proto3" json:"keyspace_id,omitempty"`
	TableId    int64  `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	IndexId    int64  `protobuf:"varint,3,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
}

func (m *SPFreshTeardownRequest) Reset()         { *m = SPFreshTeardownRequest{} }
func (m *SPFreshTeardownRequest) String() string { return proto.CompactTextString(m) }
func (*SPFreshTeardownRequest) ProtoMessage()    {}
func (*SPFreshTeardownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aabe6432836b2ba5, []int{0}
}
func (m *SPFreshTeardownRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SPFreshTeardownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SPFreshTeardownRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SPFreshTeardownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPFreshTeardownRequest.Merge(m, src)
}
func (m *SPFreshTeardownRequest) XXX_Size() int {
	return m.Size()
}
func (m *SPFreshTeardownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SPFreshTeardownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SPFreshTeardownRequest proto.InternalMessageInfo

func (m *SPFreshTeardownRequest) GetKeyspaceId() uint32 {
	if m != nil {
		return m.KeyspaceId
	}
	return 0
}

func (m *SPFreshTeardownRequest) GetTableId() int64 {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *SPFreshTeardownRequest) GetIndexId() int64 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

type SPFreshSearchRequest struct {
	KeyspaceId uint32 `protobuf:"varint,1,opt,name=keyspace_id,json=keyspaceId,proto3" json:"keyspace_id,omitempty"`
	TableId    int64  `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	IndexId    int64  `protobuf:"varint,3,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	StartTs    uint64 `protobuf:"varint,4,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	TopK       uint64 `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// query_vector_f32_le is f32 little-endian bytes, without the dims prefix.
	QueryVectorF32Le []byte        `protobuf:"bytes,6,opt,name=query_vector_f32_le,json=queryVectorF32Le,proto3" json:"query_vector_f32_le,omitempty"`
	RequiredColumns  []*ColumnInfo `protobuf:"bytes,7,rep,name=required_columns,json=requiredColumns,proto3" json:"required_columns,omitempty"`
	// Optional tuning parameters.
	OversampleFactor float64 `protobuf:"fixed64,8,opt,name=oversample_factor,json=oversampleFactor,proto3" json:"oversample_factor,omitempty"`
	// If zero, the server uses its default base beam size.
	BaseBeamSize uint32 `protobuf:"varint,9,opt,name=base_beam_size,json=baseBeamSize,proto3" json:"base_beam_size,omitempty"`
	// read_only disables background fixups (split/merge) triggered by search
	// observations. When enabled, the server must not enqueue fixups and should
	// avoid starting any background fixup workers.
	ReadOnly bool `protobuf:"varint,10,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// When true, the server populates SPFreshSearchRow.distance in each result row.
	NeedDistance bool `protobuf:"varint,11,opt,name=need_distance,json=needDistance,proto3" json:"need_distance,omitempty"`
	// Optional pushed-down scalar filter expression over the request-visible
	// filter schema. ColumnRef values are dense zero-based offsets into
	// filter_expr_columns.
	FilterExpr *Expr `protobuf:"bytes,12,opt,name=filter_expr,json=filterExpr,proto3" json:"filter_expr,omitempty"`
	// Explicit schema mapping for filter_expr ColumnRef offsets.
	FilterExprColumns []*SPFreshFilterExprColumn `protobuf:"bytes,13,rep,name=filter_expr_columns,json=filterExprColumns,proto3" json:"filter_expr_columns,omitempty"`
	// Mandatory statement evaluation properties when filter_expr is present.
	EvalContext *SPFreshEvalContext `protobuf:"bytes,14,opt,name=eval_context,json=evalContext,proto3" json:"eval_context,omitempty"`
}

func (m *SPFreshSearchRequest) Reset()         { *m = SPFreshSearchRequest{} }
func (m *SPFreshSearchRequest) String() string { return proto.CompactTextString(m) }
func (*SPFreshSearchRequest) ProtoMessage()    {}
func (*SPFreshSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aabe6432836b2ba5, []int{1}
}
func (m *SPFreshSearchRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SPFreshSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SPFreshSearchRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SPFreshSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPFreshSearchRequest.Merge(m, src)
}
func (m *SPFreshSearchRequest) XXX_Size() int {
	return m.Size()
}
func (m *SPFreshSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SPFreshSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SPFreshSearchRequest proto.InternalMessageInfo

func (m *SPFreshSearchRequest) GetKeyspaceId() uint32 {
	if m != nil {
		return m.KeyspaceId
	}
	return 0
}

func (m *SPFreshSearchRequest) GetTableId() int64 {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *SPFreshSearchRequest) GetIndexId() int64 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

func (m *SPFreshSearchRequest) GetStartTs() uint64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *SPFreshSearchRequest) GetTopK() uint64 {
	if m != nil {
		return m.TopK
	}
	return 0
}

func (m *SPFreshSearchRequest) GetQueryVectorF32Le() []byte {
	if m != nil {
		return m.QueryVectorF32Le
	}
	return nil
}

func (m *SPFreshSearchRequest) GetRequiredColumns() []*ColumnInfo {
	if m != nil {
		return m.RequiredColumns
	}
	return nil
}

func (m *SPFreshSearchRequest) GetOversampleFactor() float64 {
	if m != nil {
		return m.OversampleFactor
	}
	return 0
}

func (m *SPFreshSearchRequest) GetBaseBeamSize() uint32 {
	if m != nil {
		return m.BaseBeamSize
	}
	return 0
}

func (m *SPFreshSearchRequest) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

func (m *SPFreshSearchRequest) GetNeedDistance() bool {
	if m != nil {
		return m.NeedDistance
	}
	return false
}

func (m *SPFreshSearchRequest) GetFilterExpr() *Expr {
	if m != nil {
		return m.FilterExpr
	}
	return nil
}

func (m *SPFreshSearchRequest) GetFilterExprColumns() []*SPFreshFilterExprColumn {
	if m != nil {
		return m.FilterExprColumns
	}
	return nil
}

func (m *SPFreshSearchRequest) GetEvalContext() *SPFreshEvalContext {
	if m != nil {
		return m.EvalContext
	}
	return nil
}

type SPFreshEvalContext struct {
	TimeZoneName           string              `protobuf:"bytes,1,opt,name=time_zone_name,json=timeZoneName,proto3" json:"time_zone_name,omitempty"`
	TimeZoneOffset         int64               `protobuf:"varint,2,opt,name=time_zone_offset,json=timeZoneOffset,proto3" json:"time_zone_offset,omitempty"`
	MaxWarningCount        uint64              `protobuf:"varint,3,opt,name=max_warning_count,json=maxWarningCount,proto3" json:"max_warning_count,omitempty"`
	DivPrecisionIncrement  uint32              `protobuf:"varint,4,opt,name=div_precision_increment,json=divPrecisionIncrement,proto3" json:"div_precision_increment,omitempty"`
	TruncateMode           SPFreshTruncateMode `protobuf:"varint,5,opt,name=truncate_mode,json=truncateMode,proto3,enum=tipb.SPFreshTruncateMode" json:"truncate_mode,omitempty"`
	OverflowAsWarning      bool                `protobuf:"varint,6,opt,name=overflow_as_warning,json=overflowAsWarning,proto3" json:"overflow_as_warning,omitempty"`
	NoZeroInDate           bool                `protobuf:"varint,7,opt,name=no_zero_in_date,json=noZeroInDate,proto3" json:"no_zero_in_date,omitempty"`
	NoZeroDate             bool                `protobuf:"varint,8,opt,name=no_zero_date,json=noZeroDate,proto3" json:"no_zero_date,omitempty"`
	AllowInvalidDates      bool                `protobuf:"varint,9,opt,name=allow_invalid_dates,json=allowInvalidDates,proto3" json:"allow_invalid_dates,omitempty"`
	StrictSqlMode          bool                `protobuf:"varint,10,opt,name=strict_sql_mode,json=strictSqlMode,proto3" json:"strict_sql_mode,omitempty"`
	IgnoreZeroInDate       bool                `protobuf:"varint,11,opt,name=ignore_zero_in_date,json=ignoreZeroInDate,proto3" json:"ignore_zero_in_date,omitempty"`
	DividedByZeroAsWarning bool                `protobuf:"varint,12,opt,name=divided_by_zero_as_warning,json=dividedByZeroAsWarning,proto3" json:"divided_by_zero_as_warning,omitempty"`
	ErrorForDivisionByZero bool                `protobuf:"varint,13,opt,name=error_for_division_by_zero,json=errorForDivisionByZero,proto3" json:"error_for_division_by_zero,omitempty"`
}

func (m *SPFreshEvalContext) Reset()         { *m = SPFreshEvalContext{} }
func (m *SPFreshEvalContext) String() string { return proto.CompactTextString(m) }
func (*SPFreshEvalContext) ProtoMessage()    {}
func (*SPFreshEvalContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_aabe6432836b2ba5, []int{2}
}
func (m *SPFreshEvalContext) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SPFreshEvalContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SPFreshEvalContext.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SPFreshEvalContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPFreshEvalContext.Merge(m, src)
}
func (m *SPFreshEvalContext) XXX_Size() int {
	return m.Size()
}
func (m *SPFreshEvalContext) XXX_DiscardUnknown() {
	xxx_messageInfo_SPFreshEvalContext.DiscardUnknown(m)
}

var xxx_messageInfo_SPFreshEvalContext proto.InternalMessageInfo

func (m *SPFreshEvalContext) GetTimeZoneName() string {
	if m != nil {
		return m.TimeZoneName
	}
	return ""
}

func (m *SPFreshEvalContext) GetTimeZoneOffset() int64 {
	if m != nil {
		return m.TimeZoneOffset
	}
	return 0
}

func (m *SPFreshEvalContext) GetMaxWarningCount() uint64 {
	if m != nil {
		return m.MaxWarningCount
	}
	return 0
}

func (m *SPFreshEvalContext) GetDivPrecisionIncrement() uint32 {
	if m != nil {
		return m.DivPrecisionIncrement
	}
	return 0
}

func (m *SPFreshEvalContext) GetTruncateMode() SPFreshTruncateMode {
	if m != nil {
		return m.TruncateMode
	}
	return SPFreshTruncateMode_TruncateError
}

func (m *SPFreshEvalContext) GetOverflowAsWarning() bool {
	if m != nil {
		return m.OverflowAsWarning
	}
	return false
}

func (m *SPFreshEvalContext) GetNoZeroInDate() bool {
	if m != nil {
		return m.NoZeroInDate
	}
	return false
}

func (m *SPFreshEvalContext) GetNoZeroDate() bool {
	if m != nil {
		return m.NoZeroDate
	}
	return false
}

func (m *SPFreshEvalContext) GetAllowInvalidDates() bool {
	if m != nil {
		return m.AllowInvalidDates
	}
	return false
}

func (m *SPFreshEvalContext) GetStrictSqlMode() bool {
	if m != nil {
		return m.StrictSqlMode
	}
	return false
}

func (m *SPFreshEvalContext) GetIgnoreZeroInDate() bool {
	if m != nil {
		return m.IgnoreZeroInDate
	}
	return false
}

func (m *SPFreshEvalContext) GetDividedByZeroAsWarning() bool {
	if m != nil {
		return m.DividedByZeroAsWarning
	}
	return false
}

func (m *SPFreshEvalContext) GetErrorForDivisionByZero() bool {
	if m != nil {
		return m.ErrorForDivisionByZero
	}
	return false
}

type SPFreshFilterExprColumn struct {
	ColumnId  int64                         `protobuf:"varint,1,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	Source    SPFreshFilterExprColumnSource `protobuf:"varint,2,opt,name=source,proto3,enum=tipb.SPFreshFilterExprColumnSource" json:"source,omitempty"`
	FieldType *FieldType                    `protobuf:"bytes,3,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`
}

func (m *SPFreshFilterExprColumn) Reset()         { *m = SPFreshFilterExprColumn{} }
func (m *SPFreshFilterExprColumn) String() string { return proto.CompactTextString(m) }
func (*SPFreshFilterExprColumn) ProtoMessage()    {}
func (*SPFreshFilterExprColumn) Descriptor() ([]byte, []int) {
	return fileDescriptor_aabe6432836b2ba5, []int{3}
}
func (m *SPFreshFilterExprColumn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SPFreshFilterExprColumn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SPFreshFilterExprColumn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SPFreshFilterExprColumn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPFreshFilterExprColumn.Merge(m, src)
}
func (m *SPFreshFilterExprColumn) XXX_Size() int {
	return m.Size()
}
func (m *SPFreshFilterExprColumn) XXX_DiscardUnknown() {
	xxx_messageInfo_SPFreshFilterExprColumn.DiscardUnknown(m)
}

var xxx_messageInfo_SPFreshFilterExprColumn proto.InternalMessageInfo

func (m *SPFreshFilterExprColumn) GetColumnId() int64 {
	if m != nil {
		return m.ColumnId
	}
	return 0
}

func (m *SPFreshFilterExprColumn) GetSource() SPFreshFilterExprColumnSource {
	if m != nil {
		return m.Source
	}
	return SPFreshFilterExprColumnSource_Stored
}

func (m *SPFreshFilterExprColumn) GetFieldType() *FieldType {
	if m != nil {
		return m.FieldType
	}
	return nil
}

type SPFreshSearchResponse struct {
	Rows         []*SPFreshSearchRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Stats        *SPFreshSearchStats `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Error        *Error              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Warnings     []*Error            `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	WarningCount int64               `protobuf:"varint,5,opt,name=warning_count,json=warningCount,proto3" json:"warning_count,omitempty"`
}

func (m *SPFreshSearchResponse) Reset()         { *m = SPFreshSearchResponse{} }
func (m *SPFreshSearchResponse) String() string { return proto.CompactTextString(m) }
func (*SPFreshSearchResponse) ProtoMessage()    {}
func (*SPFreshSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aabe6432836b2ba5, []int{4}
}
func (m *SPFreshSearchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SPFreshSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SPFreshSearchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SPFreshSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPFreshSearchResponse.Merge(m, src)
}
func (m *SPFreshSearchResponse) XXX_Size() int {
	return m.Size()
}
func (m *SPFreshSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SPFreshSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SPFreshSearchResponse proto.InternalMessageInfo

func (m *SPFreshSearchResponse) GetRows() []*SPFreshSearchRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *SPFreshSearchResponse) GetStats() *SPFreshSearchStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *SPFreshSearchResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SPFreshSearchResponse) GetWarnings() []*Error {
	if m != nil {
		return m.Warnings
	}
	return nil
}

func (m *SPFreshSearchResponse) GetWarningCount() int64 {
	if m != nil {
		return m.WarningCount
	}
	return 0
}

type SPFreshSearchRow struct {
	HandleBytes  []byte   `protobuf:"bytes,1,opt,name=handle_bytes,json=handleBytes,proto3" json:"handle_bytes,omitempty"`
	Distance     float32  `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	ColumnValues [][]byte `protobuf:"bytes,3,rep,name=column_values,json=columnValues,proto3" json:"column_values,omitempty"`
}

func (m *SPFreshSearchRow) Reset()         { *m = SPFreshSearchRow{} }
func (m *SPFreshSearchRow) String() string { return proto.CompactTextString(m) }
func (*SPFreshSearchRow) ProtoMessage()    {}
func (*SPFreshSearchRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_aabe6432836b2ba5, []int{5}
}
func (m *SPFreshSearchRow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SPFreshSearchRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SPFreshSearchRow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SPFreshSearchRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPFreshSearchRow.Merge(m, src)
}
func (m *SPFreshSearchRow) XXX_Size() int {
	return m.Size()
}
func (m *SPFreshSearchRow) XXX_DiscardUnknown() {
	xxx_messageInfo_SPFreshSearchRow.DiscardUnknown(m)
}

var xxx_messageInfo_SPFreshSearchRow proto.InternalMessageInfo

func (m *SPFreshSearchRow) GetHandleBytes() []byte {
	if m != nil {
		return m.HandleBytes
	}
	return nil
}

func (m *SPFreshSearchRow) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *SPFreshSearchRow) GetColumnValues() [][]byte {
	if m != nil {
		return m.ColumnValues
	}
	return nil
}

type SPFreshSearchStats struct {
	PartitionsScanned uint64 `protobuf:"varint,1,opt,name=partitions_scanned,json=partitionsScanned,proto3" json:"partitions_scanned,omitempty"`
	VectorsScanned    uint64 `protobuf:"varint,2,opt,name=vectors_scanned,json=vectorsScanned,proto3" json:"vectors_scanned,omitempty"`
	TableLookupKeys   uint64 `protobuf:"varint,3,opt,name=table_lookup_keys,json=tableLookupKeys,proto3" json:"table_lookup_keys,omitempty"`
	TableLookupBytes  uint64 `protobuf:"varint,4,opt,name=table_lookup_bytes,json=tableLookupBytes,proto3" json:"table_lookup_bytes,omitempty"`
	// Time costs of each major stage in microseconds.
	PermitMicros      uint64 `protobuf:"varint,5,opt,name=permit_micros,json=permitMicros,proto3" json:"permit_micros,omitempty"`
	ConfigMicros      uint64 `protobuf:"varint,6,opt,name=config_micros,json=configMicros,proto3" json:"config_micros,omitempty"`
	IndexOpenMicros   uint64 `protobuf:"varint,7,opt,name=index_open_micros,json=indexOpenMicros,proto3" json:"index_open_micros,omitempty"`
	SearchMicros      uint64 `protobuf:"varint,8,opt,name=search_micros,json=searchMicros,proto3" json:"search_micros,omitempty"`
	TableLookupMicros uint64 `protobuf:"varint,9,opt,name=table_lookup_micros,json=tableLookupMicros,proto3" json:"table_lookup_micros,omitempty"`
	// Aggregated tikv-client RPC stats (best-effort) for this /spfresh_search
	// request.
	TikvClientRpcCount  uint64 `protobuf:"varint,10,opt,name=tikv_client_rpc_count,json=tikvClientRpcCount,proto3" json:"tikv_client_rpc_count,omitempty"`
	TikvClientRpcMicros uint64 `protobuf:"varint,11,opt,name=tikv_client_rpc_micros,json=tikvClientRpcMicros,proto3" json:"tikv_client_rpc_micros,omitempty"`
	ReadOnly            bool   `protobuf:"varint,12,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// Effective oversample factor used by the server for this request.
	OversampleFactor float64 `protobuf:"fixed64,13,opt,name=oversample_factor,json=oversampleFactor,proto3" json:"oversample_factor,omitempty"`
	// Process-local partition cache stats for this request.
	PartitionCacheHits   uint64 `protobuf:"varint,14,opt,name=partition_cache_hits,json=partitionCacheHits,proto3" json:"partition_cache_hits,omitempty"`
	PartitionCacheMisses uint64 `protobuf:"varint,15,opt,name=partition_cache_misses,json=partitionCacheMisses,proto3" json:"partition_cache_misses,omitempty"`
}

func (m *SPFreshSearchStats) Reset()         { *m = SPFreshSearchStats{} }
func (m *SPFreshSearchStats) String() string { return proto.CompactTextString(m) }
func (*SPFreshSearchStats) ProtoMessage()    {}
func (*SPFreshSearchStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_aabe6432836b2ba5, []int{6}
}
func (m *SPFreshSearchStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SPFreshSearchStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SPFreshSearchStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SPFreshSearchStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPFreshSearchStats.Merge(m, src)
}
func (m *SPFreshSearchStats) XXX_Size() int {
	return m.Size()
}
func (m *SPFreshSearchStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SPFreshSearchStats.DiscardUnknown(m)
}

var xxx_messageInfo_SPFreshSearchStats proto.InternalMessageInfo

func (m *SPFreshSearchStats) GetPartitionsScanned() uint64 {
	if m != nil {
		return m.PartitionsScanned
	}
	return 0
}

func (m *SPFreshSearchStats) GetVectorsScanned() uint64 {
	if m != nil {
		return m.VectorsScanned
	}
	return 0
}

func (m *SPFreshSearchStats) GetTableLookupKeys() uint64 {
	if m != nil {
		return m.TableLookupKeys
	}
	return 0
}

func (m *SPFreshSearchStats) GetTableLookupBytes() uint64 {
	if m != nil {
		return m.TableLookupBytes
	}
	return 0
}

func (m *SPFreshSearchStats) GetPermitMicros() uint64 {
	if m != nil {
		return m.PermitMicros
	}
	return 0
}

func (m *SPFreshSearchStats) GetConfigMicros() uint64 {
	if m != nil {
		return m.ConfigMicros
	}
	return 0
}

func (m *SPFreshSearchStats) GetIndexOpenMicros() uint64 {
	if m != nil {
		return m.IndexOpenMicros
	}
	return 0
}

func (m *SPFreshSearchStats) GetSearchMicros() uint64 {
	if m != nil {
		return m.SearchMicros
	}
	return 0
}

func (m *SPFreshSearchStats) GetTableLookupMicros() uint64 {
	if m != nil {
		return m.TableLookupMicros
	}
	return 0
}

func (m *SPFreshSearchStats) GetTikvClientRpcCount() uint64 {
	if m != nil {
		return m.TikvClientRpcCount
	}
	return 0
}

func (m *SPFreshSearchStats) GetTikvClientRpcMicros() uint64 {
	if m != nil {
		return m.TikvClientRpcMicros
	}
	return 0
}

func (m *SPFreshSearchStats) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

func (m *SPFreshSearchStats) GetOversampleFactor() float64 {
	if m != nil {
		return m.OversampleFactor
	}
	return 0
}

func (m *SPFreshSearchStats) GetPartitionCacheHits() uint64 {
	if m != nil {
		return m.PartitionCacheHits
	}
	return 0
}

func (m *SPFreshSearchStats) GetPartitionCacheMisses() uint64 {
	if m != nil {
		return m.PartitionCacheMisses
	}
	return 0
}

func init() {
	proto.RegisterEnum("tipb.SPFreshTruncateMode", SPFreshTruncateMode_name, SPFreshTruncateMode_value)
	proto.RegisterEnum("tipb.SPFreshFilterExprColumnSource", SPFreshFilterExprColumnSource_name, SPFreshFilterExprColumnSource_value)
	proto.RegisterType((*SPFreshTeardownRequest)(nil), "tipb.SPFreshTeardownRequest")
	proto.RegisterType((*SPFreshSearchRequest)(nil), "tipb.SPFreshSearchRequest")
	proto.RegisterType((*SPFreshEvalContext)(nil), "tipb.SPFreshEvalContext")
	proto.RegisterType((*SPFreshFilterExprColumn)(nil), "tipb.SPFreshFilterExprColumn")
	proto.RegisterType((*SPFreshSearchResponse)(nil), "tipb.SPFreshSearchResponse")
	proto.RegisterType((*SPFreshSearchRow)(nil), "tipb.SPFreshSearchRow")
	proto.RegisterType((*SPFreshSearchStats)(nil), "tipb.SPFreshSearchStats")
}

func init() { proto.RegisterFile("spfresh.proto", fileDescriptor_aabe6432836b2ba5) }

var fileDescriptor_aabe6432836b2ba5 = []byte{
	// 1388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcf, 0x6f, 0x23, 0xb7,
	0x15, 0xf6, 0xac, 0x65, 0x5b, 0x7e, 0x1a, 0x59, 0x12, 0xb5, 0xeb, 0x4c, 0x5c, 0xc4, 0x55, 0xbc,
	0x6d, 0x23, 0x38, 0x5d, 0xb5, 0xf5, 0x16, 0x2d, 0x9a, 0x05, 0x0a, 0x74, 0xbd, 0x31, 0x22, 0x24,
	0xdb, 0xdd, 0x8e, 0x8c, 0x14, 0xc8, 0x85, 0xa0, 0x66, 0x9e, 0x6c, 0xc2, 0x33, 0xe4, 0x98, 0xa4,
	0x64, 0xcb, 0xa7, 0xfe, 0x09, 0x3d, 0xf6, 0xde, 0x4b, 0x81, 0xfe, 0x23, 0x3d, 0xe6, 0xd6, 0x1c,
	0x8b, 0x75, 0xff, 0x90, 0x82, 0xe4, 0x8c, 0xf5, 0xa3, 0x49, 0x6e, 0xb9, 0x91, 0xdf, 0xf7, 0x3d,
	0xfe, 0x78, 0xf3, 0xf1, 0xbd, 0x81, 0xa6, 0x2e, 0x26, 0x0a, 0xf5, 0xe5, 0xa0, 0x50, 0xd2, 0x48,
	0x52, 0x33, 0xbc, 0x18, 0x1f, 0xb4, 0xf1, 0xb6, 0x50, 0xa8, 0x35, 0x97, 0xc2, 0xe3, 0x07, 0xa1,
	0x4e, 0x2e, 0x31, 0x67, 0x0f, 0x33, 0xcc, 0x30, 0x31, 0xe5, 0xec, 0xf1, 0x85, 0xbc, 0x90, 0x6e,
	0xf8, 0x0b, 0x3b, 0x2a, 0xd1, 0x96, 0x9a, 0x6a, 0xe3, 0x86, 0x1e, 0x38, 0x92, 0xb0, 0x3f, 0x7a,
	0x7b, 0x66, 0xf7, 0x3a, 0x47, 0xa6, 0x52, 0x79, 0x23, 0x62, 0xbc, 0x9e, 0xa2, 0x36, 0xe4, 0xc7,
	0xd0, 0xb8, 0xc2, 0xb9, 0x2e, 0x58, 0x82, 0x94, 0xa7, 0x51, 0xd0, 0x0b, 0xfa, 0xcd, 0x18, 0x2a,
	0x68, 0x98, 0x92, 0xf7, 0xa1, 0x6e, 0xd8, 0x38, 0x73, 0xec, 0xa3, 0x5e, 0xd0, 0xdf, 0x8c, 0x77,
	0xdc, 0xdc, 0x53, 0x5c, 0xa4, 0x78, 0x6b, 0xa9, 0x4d, 0x4f, 0xb9, 0xf9, 0x30, 0x3d, 0xfa, 0x77,
	0x0d, 0x1e, 0x97, 0x3b, 0x8e, 0x90, 0xa9, 0xe4, 0xf2, 0x87, 0xdd, 0xcf, 0x52, 0xda, 0x30, 0x65,
	0xa8, 0xd1, 0x51, 0xad, 0x17, 0xf4, 0x6b, 0xf1, 0x8e, 0x9b, 0x9f, 0x6b, 0xd2, 0x85, 0x2d, 0x23,
	0x0b, 0x7a, 0x15, 0x6d, 0x39, 0xbc, 0x66, 0x64, 0xf1, 0x39, 0x79, 0x06, 0xdd, 0xeb, 0x29, 0xaa,
	0x39, 0x9d, 0x61, 0x62, 0xa4, 0xa2, 0x93, 0xe7, 0x27, 0x34, 0xc3, 0x68, 0xbb, 0x17, 0xf4, 0xc3,
	0xb8, 0xed, 0xa8, 0x2f, 0x1d, 0x73, 0xf6, 0xfc, 0xe4, 0x0b, 0x24, 0x2f, 0xa0, 0xad, 0xf0, 0x7a,
	0xca, 0x15, 0xa6, 0x34, 0x91, 0xd9, 0x34, 0x17, 0x3a, 0xda, 0xe9, 0x6d, 0xf6, 0x1b, 0x27, 0xed,
	0x81, 0xfd, 0x6a, 0x83, 0x53, 0x07, 0x0e, 0xc5, 0x44, 0xc6, 0xad, 0x4a, 0xe9, 0x31, 0x4d, 0x3e,
	0x86, 0x8e, 0x9c, 0xa1, 0xd2, 0x2c, 0x2f, 0x32, 0xa4, 0x13, 0x66, 0x97, 0x8d, 0xea, 0xbd, 0xa0,
	0x1f, 0xc4, 0xed, 0x05, 0x71, 0xe6, 0x70, 0xf2, 0x13, 0xd8, 0x1b, 0x33, 0x8d, 0x74, 0x8c, 0x2c,
	0xa7, 0x9a, 0xdf, 0x61, 0xb4, 0xeb, 0x52, 0x14, 0x5a, 0xf4, 0x25, 0xb2, 0x7c, 0xc4, 0xef, 0x90,
	0xfc, 0x08, 0x76, 0x15, 0xb2, 0x94, 0x4a, 0x91, 0xcd, 0x23, 0xe8, 0x05, 0xfd, 0x7a, 0x5c, 0xb7,
	0xc0, 0x1b, 0x91, 0xcd, 0xc9, 0x53, 0x68, 0x0a, 0xc4, 0x94, 0xa6, 0x5c, 0x1b, 0x26, 0x12, 0x8c,
	0x1a, 0x4e, 0x10, 0x5a, 0xf0, 0x55, 0x89, 0x91, 0x8f, 0xa1, 0x31, 0xe1, 0x99, 0x41, 0x45, 0xad,
	0xdf, 0xa2, 0xb0, 0x17, 0xf4, 0x1b, 0x27, 0xe0, 0x2f, 0xf3, 0xe9, 0x6d, 0xa1, 0x62, 0xf0, 0xb4,
	0x1d, 0x93, 0xd7, 0xd0, 0x5d, 0x12, 0x3f, 0x64, 0xa0, 0xe9, 0x32, 0xf0, 0x81, 0x0f, 0x2a, 0xbf,
	0xf6, 0xd9, 0x43, 0x94, 0xbf, 0x7e, 0xdc, 0x99, 0xac, 0x21, 0x9a, 0xbc, 0x80, 0x10, 0x67, 0x2c,
	0xa3, 0x89, 0x14, 0x06, 0x6f, 0x4d, 0xb4, 0xe7, 0x36, 0x8f, 0x56, 0xd6, 0xf9, 0x74, 0xc6, 0xb2,
	0x53, 0xcf, 0xc7, 0x0d, 0x5c, 0x4c, 0x8e, 0xfe, 0xb2, 0x05, 0xe4, 0xff, 0x35, 0x36, 0x6f, 0x86,
	0xe7, 0x48, 0xef, 0xa4, 0x40, 0x2a, 0x58, 0x8e, 0xce, 0x5a, 0xbb, 0x71, 0x68, 0xd1, 0xaf, 0xa4,
	0xc0, 0x3f, 0xb2, 0x1c, 0x49, 0x1f, 0xda, 0x0b, 0x95, 0x9c, 0x4c, 0x34, 0x9a, 0xd2, 0x64, 0x7b,
	0x95, 0xee, 0x8d, 0x43, 0xc9, 0x31, 0x74, 0x72, 0x76, 0x4b, 0x6f, 0x98, 0x12, 0x5c, 0x5c, 0xd0,
	0x44, 0x4e, 0x85, 0x71, 0xa6, 0xab, 0xc5, 0xad, 0x9c, 0xdd, 0xfe, 0xd9, 0xe3, 0xa7, 0x16, 0x26,
	0xbf, 0x81, 0xf7, 0x52, 0x3e, 0xa3, 0x85, 0xc2, 0x84, 0xdb, 0x77, 0x4b, 0xb9, 0x48, 0x14, 0xe6,
	0x28, 0x8c, 0xf3, 0x62, 0x33, 0x7e, 0x92, 0xf2, 0xd9, 0xdb, 0x8a, 0x1d, 0x56, 0x24, 0xf9, 0x3d,
	0x34, 0x8d, 0x9a, 0x8a, 0x84, 0x19, 0xa4, 0xb9, 0x4c, 0xd1, 0x39, 0x74, 0xef, 0xe4, 0xfd, 0x95,
	0x44, 0x9c, 0x97, 0x8a, 0xd7, 0x32, 0xc5, 0x38, 0x34, 0x4b, 0x33, 0x32, 0x80, 0xae, 0xf5, 0xcf,
	0x24, 0x93, 0x37, 0x94, 0xe9, 0xea, 0xac, 0xce, 0xc4, 0xf5, 0xb8, 0x53, 0x51, 0x7f, 0xd0, 0xe5,
	0x61, 0xc9, 0x4f, 0xa1, 0x25, 0x24, 0xbd, 0x43, 0x25, 0x29, 0x17, 0x34, 0x65, 0x06, 0xa3, 0x9d,
	0xd2, 0x1a, 0xf2, 0x2b, 0x54, 0x72, 0x28, 0x5e, 0x31, 0x83, 0xa4, 0x07, 0x61, 0x25, 0x73, 0x9a,
	0xba, 0xd3, 0x80, 0xd7, 0x38, 0xc5, 0x00, 0xba, 0x2c, 0xb3, 0xbb, 0x72, 0x31, 0x63, 0x19, 0x4f,
	0x9d, 0x4e, 0x3b, 0xa7, 0xd6, 0xe3, 0x8e, 0xa3, 0x86, 0x9e, 0xb1, 0x72, 0x4d, 0x7e, 0x06, 0x2d,
	0x6d, 0x14, 0x4f, 0x0c, 0xd5, 0xd7, 0x99, 0xbf, 0xaa, 0x37, 0x6d, 0xd3, 0xc3, 0xa3, 0xeb, 0xcc,
	0x5d, 0xe8, 0x19, 0x74, 0xf9, 0x85, 0x90, 0x0a, 0x57, 0x0f, 0xe9, 0xfd, 0xdb, 0xf6, 0xd4, 0xd2,
	0x41, 0x3f, 0x81, 0x83, 0x94, 0xcf, 0x78, 0x8a, 0x29, 0x1d, 0xcf, 0x7d, 0xc8, 0x52, 0x1a, 0x42,
	0x17, 0xb5, 0x5f, 0x2a, 0x5e, 0xce, 0x6d, 0xe0, 0x22, 0x17, 0x9f, 0xc0, 0x01, 0x2a, 0x65, 0x5f,
	0xbe, 0x54, 0xd4, 0x6a, 0xdc, 0x87, 0x2b, 0x97, 0x89, 0x9a, 0x3e, 0xd6, 0x29, 0xce, 0xa4, 0x7a,
	0x55, 0xf2, 0x7e, 0x91, 0xa3, 0xbf, 0x07, 0xf0, 0xde, 0x77, 0xd8, 0xdd, 0xbe, 0x4c, 0xff, 0x3c,
	0xaa, 0xea, 0xb6, 0x19, 0xd7, 0x3d, 0x30, 0x4c, 0xc9, 0x0b, 0xd8, 0xd6, 0x72, 0xaa, 0x12, 0x74,
	0xa6, 0xdb, 0x3b, 0x79, 0xfa, 0xbd, 0x4f, 0x67, 0xe4, 0xa4, 0x71, 0x19, 0x42, 0x06, 0x00, 0x13,
	0x8e, 0x59, 0x4a, 0xcd, 0xbc, 0x40, 0x67, 0xc5, 0xc6, 0x49, 0xcb, 0x2f, 0x70, 0x66, 0xf1, 0xf3,
	0x79, 0x81, 0xf1, 0xee, 0xa4, 0x1a, 0x1e, 0xfd, 0x37, 0x80, 0x27, 0x6b, 0x25, 0x58, 0x17, 0x52,
	0x68, 0x24, 0xc7, 0x50, 0x53, 0xf2, 0x46, 0x47, 0x81, 0x7b, 0xbf, 0xfb, 0x2b, 0x87, 0x28, 0xa5,
	0xf2, 0x26, 0x76, 0x1a, 0x32, 0x80, 0x2d, 0x6d, 0x98, 0xd1, 0xee, 0xc4, 0xeb, 0x8f, 0xd4, 0x8b,
	0x47, 0x96, 0x8f, 0xbd, 0x8c, 0x7c, 0x08, 0x5b, 0x2e, 0x6b, 0xe5, 0x01, 0x1b, 0x65, 0x45, 0xb1,
	0x50, 0xec, 0x19, 0xf2, 0x11, 0xd4, 0xcb, 0x6f, 0x64, 0x6b, 0xf5, 0xe6, 0xba, 0xea, 0x81, 0xb4,
	0x85, 0x6c, 0xf5, 0xfd, 0x6d, 0xb9, 0x7c, 0x86, 0x37, 0x4b, 0x8f, 0xef, 0x68, 0x06, 0xed, 0xf5,
	0xa3, 0x93, 0x0f, 0x21, 0xbc, 0x64, 0x22, 0xcd, 0x90, 0x8e, 0xe7, 0xd6, 0x98, 0x81, 0x2b, 0xeb,
	0x0d, 0x8f, 0xbd, 0xb4, 0x10, 0x39, 0x80, 0xfa, 0x43, 0x7d, 0xb4, 0x57, 0x7b, 0x14, 0x3f, 0xcc,
	0xed, 0xbe, 0xe5, 0x37, 0x9c, 0xb1, 0x6c, 0x8a, 0x3a, 0xda, 0xec, 0x6d, 0xf6, 0xc3, 0x38, 0xf4,
	0xe0, 0x97, 0x0e, 0x3b, 0xfa, 0xe7, 0xa2, 0x0e, 0x2d, 0xa5, 0x81, 0x3c, 0x03, 0x52, 0x30, 0x65,
	0xb8, 0xe1, 0x52, 0x68, 0xaa, 0x13, 0x26, 0x04, 0x7a, 0x23, 0xd4, 0xe2, 0xce, 0x82, 0x19, 0x79,
	0x82, 0x7c, 0x04, 0x2d, 0xdf, 0x81, 0x16, 0xda, 0x47, 0x4e, 0xbb, 0x57, 0xc2, 0x95, 0xf0, 0x18,
	0x3a, 0xbe, 0x2d, 0x66, 0x52, 0x5e, 0x4d, 0x0b, 0x6a, 0x3b, 0x66, 0x55, 0x8f, 0x1c, 0xf1, 0x85,
	0xc3, 0x3f, 0xc7, 0xb9, 0x26, 0x3f, 0x07, 0xb2, 0xa2, 0xf5, 0x49, 0xf0, 0x6d, 0xb1, 0xbd, 0x24,
	0xf6, 0x99, 0x78, 0x0a, 0xcd, 0x02, 0x55, 0xce, 0x0d, 0xcd, 0x79, 0xa2, 0xa4, 0x2e, 0xfb, 0x64,
	0xe8, 0xc1, 0xd7, 0x0e, 0xf3, 0x29, 0x11, 0x13, 0x7e, 0x51, 0x89, 0xb6, 0xbd, 0xc8, 0x83, 0xa5,
	0xe8, 0x18, 0x3a, 0xbe, 0x3f, 0xcb, 0x02, 0x45, 0x25, 0xdc, 0xf1, 0x67, 0x74, 0xc4, 0x9b, 0x02,
	0xc5, 0x62, 0x41, 0xed, 0xd2, 0x56, 0xe9, 0xea, 0x7e, 0x41, 0x0f, 0x96, 0xa2, 0x01, 0x74, 0x57,
	0x2e, 0x52, 0x4a, 0x77, 0x7d, 0x36, 0x97, 0x6e, 0x52, 0xea, 0x7f, 0x05, 0x4f, 0x0c, 0xbf, 0x9a,
	0xd1, 0x24, 0xe3, 0x28, 0x0c, 0x55, 0x45, 0x52, 0x1a, 0x07, 0x5c, 0x04, 0xb1, 0xe4, 0xa9, 0xe3,
	0xe2, 0x22, 0xf1, 0xb5, 0xfb, 0x39, 0xec, 0xaf, 0x87, 0x94, 0xbb, 0x34, 0x5c, 0x4c, 0x77, 0x25,
	0xa6, 0xdc, 0x67, 0xa5, 0xfd, 0x86, 0x6b, 0xed, 0xf7, 0x5b, 0xdb, 0x7d, 0xf3, 0x3b, 0xda, 0xfd,
	0x2f, 0xe1, 0xf1, 0x83, 0x29, 0x68, 0xc2, 0x92, 0x4b, 0xa4, 0x97, 0xdc, 0x68, 0xd7, 0x12, 0x6b,
	0xf1, 0xc2, 0x4a, 0xa7, 0x96, 0xfa, 0x8c, 0x1b, 0x4d, 0x7e, 0x0d, 0xfb, 0xeb, 0x11, 0x39, 0xd7,
	0x1a, 0x75, 0xd4, 0x72, 0x31, 0x8f, 0x57, 0x63, 0x5e, 0x3b, 0xee, 0xf8, 0x4f, 0xd0, 0xfd, 0x96,
	0x7e, 0x42, 0x3a, 0xd0, 0xac, 0xe6, 0xee, 0xf1, 0xb5, 0x37, 0x08, 0x81, 0xbd, 0x0a, 0x1a, 0xba,
	0x82, 0xdb, 0x0e, 0x48, 0x17, 0x5a, 0x15, 0x56, 0xd6, 0xcf, 0xf6, 0xa3, 0xe3, 0xdf, 0xc2, 0x07,
	0xdf, 0x5b, 0xb8, 0x08, 0xc0, 0xf6, 0xc8, 0x48, 0x85, 0x69, 0x7b, 0xc3, 0x8e, 0x3f, 0x73, 0xaf,
	0xaf, 0x1d, 0xbc, 0xfc, 0xdd, 0x37, 0xff, 0xa8, 0x07, 0xff, 0x7a, 0x77, 0x18, 0x7c, 0xfd, 0xee,
	0x30, 0xf8, 0xcf, 0xbb, 0xc3, 0xe0, 0xaf, 0xf7, 0x87, 0x1b, 0x7f, 0xbb, 0x3f, 0xdc, 0xf8, 0xfa,
	0xfe, 0x70, 0xe3, 0x9b, 0xfb, 0xc3, 0x0d, 0x78, 0x92, 0xc8, 0x7c, 0x50, 0x70, 0x71, 0x91, 0xb0,
	0x62, 0x60, 0x78, 0x3a, 0x76, 0xf5, 0xe1, 0x6d, 0x30, 0xde, 0x76, 0xbf, 0xb3, 0xcf, 0xff, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x97, 0xbc, 0xa4, 0x8e, 0x3a, 0x0b, 0x00, 0x00,
}

func (m *SPFreshTeardownRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SPFreshTeardownRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SPFreshTeardownRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IndexId != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.IndexId))
		i--
		dAtA[i] = 0x18
	}
	if m.TableId != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.TableId))
		i--
		dAtA[i] = 0x10
	}
	if m.KeyspaceId != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.KeyspaceId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SPFreshSearchRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SPFreshSearchRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SPFreshSearchRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EvalContext != nil {
		{
			size, err := m.EvalContext.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSpfresh(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x72
	}
	if len(m.FilterExprColumns) > 0 {
		for iNdEx := len(m.FilterExprColumns) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FilterExprColumns[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSpfresh(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if m.FilterExpr != nil {
		{
			size, err := m.FilterExpr.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSpfresh(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	if m.NeedDistance {
		i--
		if m.NeedDistance {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.ReadOnly {
		i--
		if m.ReadOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.BaseBeamSize != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.BaseBeamSize))
		i--
		dAtA[i] = 0x48
	}
	if m.OversampleFactor != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.OversampleFactor))))
		i--
		dAtA[i] = 0x41
	}
	if len(m.RequiredColumns) > 0 {
		for iNdEx := len(m.RequiredColumns) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RequiredColumns[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSpfresh(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.QueryVectorF32Le) > 0 {
		i -= len(m.QueryVectorF32Le)
		copy(dAtA[i:], m.QueryVectorF32Le)
		i = encodeVarintSpfresh(dAtA, i, uint64(len(m.QueryVectorF32Le)))
		i--
		dAtA[i] = 0x32
	}
	if m.TopK != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.TopK))
		i--
		dAtA[i] = 0x28
	}
	if m.StartTs != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.StartTs))
		i--
		dAtA[i] = 0x20
	}
	if m.IndexId != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.IndexId))
		i--
		dAtA[i] = 0x18
	}
	if m.TableId != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.TableId))
		i--
		dAtA[i] = 0x10
	}
	if m.KeyspaceId != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.KeyspaceId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SPFreshEvalContext) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SPFreshEvalContext) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SPFreshEvalContext) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ErrorForDivisionByZero {
		i--
		if m.ErrorForDivisionByZero {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if m.DividedByZeroAsWarning {
		i--
		if m.DividedByZeroAsWarning {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.IgnoreZeroInDate {
		i--
		if m.IgnoreZeroInDate {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.StrictSqlMode {
		i--
		if m.StrictSqlMode {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.AllowInvalidDates {
		i--
		if m.AllowInvalidDates {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.NoZeroDate {
		i--
		if m.NoZeroDate {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.NoZeroInDate {
		i--
		if m.NoZeroInDate {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.OverflowAsWarning {
		i--
		if m.OverflowAsWarning {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.TruncateMode != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.TruncateMode))
		i--
		dAtA[i] = 0x28
	}
	if m.DivPrecisionIncrement != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.DivPrecisionIncrement))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxWarningCount != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.MaxWarningCount))
		i--
		dAtA[i] = 0x18
	}
	if m.TimeZoneOffset != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.TimeZoneOffset))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TimeZoneName) > 0 {
		i -= len(m.TimeZoneName)
		copy(dAtA[i:], m.TimeZoneName)
		i = encodeVarintSpfresh(dAtA, i, uint64(len(m.TimeZoneName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SPFreshFilterExprColumn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SPFreshFilterExprColumn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SPFreshFilterExprColumn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FieldType != nil {
		{
			size, err := m.FieldType.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSpfresh(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Source != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.Source))
		i--
		dAtA[i] = 0x10
	}
	if m.ColumnId != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.ColumnId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SPFreshSearchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SPFreshSearchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SPFreshSearchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WarningCount != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.WarningCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Warnings) > 0 {
		for iNdEx := len(m.Warnings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Warnings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSpfresh(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Error != nil {
		{
			size, err := m.Error.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSpfresh(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Stats != nil {
		{
			size, err := m.Stats.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSpfresh(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Rows) > 0 {
		for iNdEx := len(m.Rows) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rows[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSpfresh(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *SPFreshSearchRow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SPFreshSearchRow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SPFreshSearchRow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ColumnValues) > 0 {
		for iNdEx := len(m.ColumnValues) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ColumnValues[iNdEx])
			copy(dAtA[i:], m.ColumnValues[iNdEx])
			i = encodeVarintSpfresh(dAtA, i, uint64(len(m.ColumnValues[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Distance != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Distance))))
		i--
		dAtA[i] = 0x15
	}
	if len(m.HandleBytes) > 0 {
		i -= len(m.HandleBytes)
		copy(dAtA[i:], m.HandleBytes)
		i = encodeVarintSpfresh(dAtA, i, uint64(len(m.HandleBytes)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SPFreshSearchStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SPFreshSearchStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SPFreshSearchStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PartitionCacheMisses != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.PartitionCacheMisses))
		i--
		dAtA[i] = 0x78
	}
	if m.PartitionCacheHits != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.PartitionCacheHits))
		i--
		dAtA[i] = 0x70
	}
	if m.OversampleFactor != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.OversampleFactor))))
		i--
		dAtA[i] = 0x69
	}
	if m.ReadOnly {
		i--
		if m.ReadOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.TikvClientRpcMicros != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.TikvClientRpcMicros))
		i--
		dAtA[i] = 0x58
	}
	if m.TikvClientRpcCount != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.TikvClientRpcCount))
		i--
		dAtA[i] = 0x50
	}
	if m.TableLookupMicros != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.TableLookupMicros))
		i--
		dAtA[i] = 0x48
	}
	if m.SearchMicros != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.SearchMicros))
		i--
		dAtA[i] = 0x40
	}
	if m.IndexOpenMicros != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.IndexOpenMicros))
		i--
		dAtA[i] = 0x38
	}
	if m.ConfigMicros != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.ConfigMicros))
		i--
		dAtA[i] = 0x30
	}
	if m.PermitMicros != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.PermitMicros))
		i--
		dAtA[i] = 0x28
	}
	if m.TableLookupBytes != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.TableLookupBytes))
		i--
		dAtA[i] = 0x20
	}
	if m.TableLookupKeys != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.TableLookupKeys))
		i--
		dAtA[i] = 0x18
	}
	if m.VectorsScanned != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.VectorsScanned))
		i--
		dAtA[i] = 0x10
	}
	if m.PartitionsScanned != 0 {
		i = encodeVarintSpfresh(dAtA, i, uint64(m.PartitionsScanned))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSpfresh(dAtA []byte, offset int, v uint64) int {
	offset -= sovSpfresh(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SPFreshTeardownRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KeyspaceId != 0 {
		n += 1 + sovSpfresh(uint64(m.KeyspaceId))
	}
	if m.TableId != 0 {
		n += 1 + sovSpfresh(uint64(m.TableId))
	}
	if m.IndexId != 0 {
		n += 1 + sovSpfresh(uint64(m.IndexId))
	}
	return n
}

func (m *SPFreshSearchRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KeyspaceId != 0 {
		n += 1 + sovSpfresh(uint64(m.KeyspaceId))
	}
	if m.TableId != 0 {
		n += 1 + sovSpfresh(uint64(m.TableId))
	}
	if m.IndexId != 0 {
		n += 1 + sovSpfresh(uint64(m.IndexId))
	}
	if m.StartTs != 0 {
		n += 1 + sovSpfresh(uint64(m.StartTs))
	}
	if m.TopK != 0 {
		n += 1 + sovSpfresh(uint64(m.TopK))
	}
	l = len(m.QueryVectorF32Le)
	if l > 0 {
		n += 1 + l + sovSpfresh(uint64(l))
	}
	if len(m.RequiredColumns) > 0 {
		for _, e := range m.RequiredColumns {
			l = e.Size()
			n += 1 + l + sovSpfresh(uint64(l))
		}
	}
	if m.OversampleFactor != 0 {
		n += 9
	}
	if m.BaseBeamSize != 0 {
		n += 1 + sovSpfresh(uint64(m.BaseBeamSize))
	}
	if m.ReadOnly {
		n += 2
	}
	if m.NeedDistance {
		n += 2
	}
	if m.FilterExpr != nil {
		l = m.FilterExpr.Size()
		n += 1 + l + sovSpfresh(uint64(l))
	}
	if len(m.FilterExprColumns) > 0 {
		for _, e := range m.FilterExprColumns {
			l = e.Size()
			n += 1 + l + sovSpfresh(uint64(l))
		}
	}
	if m.EvalContext != nil {
		l = m.EvalContext.Size()
		n += 1 + l + sovSpfresh(uint64(l))
	}
	return n
}

func (m *SPFreshEvalContext) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TimeZoneName)
	if l > 0 {
		n += 1 + l + sovSpfresh(uint64(l))
	}
	if m.TimeZoneOffset != 0 {
		n += 1 + sovSpfresh(uint64(m.TimeZoneOffset))
	}
	if m.MaxWarningCount != 0 {
		n += 1 + sovSpfresh(uint64(m.MaxWarningCount))
	}
	if m.DivPrecisionIncrement != 0 {
		n += 1 + sovSpfresh(uint64(m.DivPrecisionIncrement))
	}
	if m.TruncateMode != 0 {
		n += 1 + sovSpfresh(uint64(m.TruncateMode))
	}
	if m.OverflowAsWarning {
		n += 2
	}
	if m.NoZeroInDate {
		n += 2
	}
	if m.NoZeroDate {
		n += 2
	}
	if m.AllowInvalidDates {
		n += 2
	}
	if m.StrictSqlMode {
		n += 2
	}
	if m.IgnoreZeroInDate {
		n += 2
	}
	if m.DividedByZeroAsWarning {
		n += 2
	}
	if m.ErrorForDivisionByZero {
		n += 2
	}
	return n
}

func (m *SPFreshFilterExprColumn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ColumnId != 0 {
		n += 1 + sovSpfresh(uint64(m.ColumnId))
	}
	if m.Source != 0 {
		n += 1 + sovSpfresh(uint64(m.Source))
	}
	if m.FieldType != nil {
		l = m.FieldType.Size()
		n += 1 + l + sovSpfresh(uint64(l))
	}
	return n
}

func (m *SPFreshSearchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Rows) > 0 {
		for _, e := range m.Rows {
			l = e.Size()
			n += 1 + l + sovSpfresh(uint64(l))
		}
	}
	if m.Stats != nil {
		l = m.Stats.Size()
		n += 1 + l + sovSpfresh(uint64(l))
	}
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovSpfresh(uint64(l))
	}
	if len(m.Warnings) > 0 {
		for _, e := range m.Warnings {
			l = e.Size()
			n += 1 + l + sovSpfresh(uint64(l))
		}
	}
	if m.WarningCount != 0 {
		n += 1 + sovSpfresh(uint64(m.WarningCount))
	}
	return n
}

func (m *SPFreshSearchRow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.HandleBytes)
	if l > 0 {
		n += 1 + l + sovSpfresh(uint64(l))
	}
	if m.Distance != 0 {
		n += 5
	}
	if len(m.ColumnValues) > 0 {
		for _, b := range m.ColumnValues {
			l = len(b)
			n += 1 + l + sovSpfresh(uint64(l))
		}
	}
	return n
}

func (m *SPFreshSearchStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PartitionsScanned != 0 {
		n += 1 + sovSpfresh(uint64(m.PartitionsScanned))
	}
	if m.VectorsScanned != 0 {
		n += 1 + sovSpfresh(uint64(m.VectorsScanned))
	}
	if m.TableLookupKeys != 0 {
		n += 1 + sovSpfresh(uint64(m.TableLookupKeys))
	}
	if m.TableLookupBytes != 0 {
		n += 1 + sovSpfresh(uint64(m.TableLookupBytes))
	}
	if m.PermitMicros != 0 {
		n += 1 + sovSpfresh(uint64(m.PermitMicros))
	}
	if m.ConfigMicros != 0 {
		n += 1 + sovSpfresh(uint64(m.ConfigMicros))
	}
	if m.IndexOpenMicros != 0 {
		n += 1 + sovSpfresh(uint64(m.IndexOpenMicros))
	}
	if m.SearchMicros != 0 {
		n += 1 + sovSpfresh(uint64(m.SearchMicros))
	}
	if m.TableLookupMicros != 0 {
		n += 1 + sovSpfresh(uint64(m.TableLookupMicros))
	}
	if m.TikvClientRpcCount != 0 {
		n += 1 + sovSpfresh(uint64(m.TikvClientRpcCount))
	}
	if m.TikvClientRpcMicros != 0 {
		n += 1 + sovSpfresh(uint64(m.TikvClientRpcMicros))
	}
	if m.ReadOnly {
		n += 2
	}
	if m.OversampleFactor != 0 {
		n += 9
	}
	if m.PartitionCacheHits != 0 {
		n += 1 + sovSpfresh(uint64(m.PartitionCacheHits))
	}
	if m.PartitionCacheMisses != 0 {
		n += 1 + sovSpfresh(uint64(m.PartitionCacheMisses))
	}
	return n
}

func sovSpfresh(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSpfresh(x uint64) (n int) {
	return sovSpfresh(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SPFreshTeardownRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpfresh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SPFreshTeardownRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SPFreshTeardownRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyspaceId", wireType)
			}
			m.KeyspaceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyspaceId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			m.TableId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexId", wireType)
			}
			m.IndexId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSpfresh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpfresh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SPFreshSearchRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpfresh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SPFreshSearchRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SPFreshSearchRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyspaceId", wireType)
			}
			m.KeyspaceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyspaceId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			m.TableId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexId", wireType)
			}
			m.IndexId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTs", wireType)
			}
			m.StartTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopK", wireType)
			}
			m.TopK = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TopK |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryVectorF32Le", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryVectorF32Le = append(m.QueryVectorF32Le[:0], dAtA[iNdEx:postIndex]...)
			if m.QueryVectorF32Le == nil {
				m.QueryVectorF32Le = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredColumns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequiredColumns = append(m.RequiredColumns, &ColumnInfo{})
			if err := m.RequiredColumns[len(m.RequiredColumns)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field OversampleFactor", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.OversampleFactor = float64(math.Float64frombits(v))
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseBeamSize", wireType)
			}
			m.BaseBeamSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseBeamSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReadOnly = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NeedDistance", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NeedDistance = bool(v != 0)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilterExpr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FilterExpr == nil {
				m.FilterExpr = &Expr{}
			}
			if err := m.FilterExpr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilterExprColumns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FilterExprColumns = append(m.FilterExprColumns, &SPFreshFilterExprColumn{})
			if err := m.FilterExprColumns[len(m.FilterExprColumns)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvalContext", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EvalContext == nil {
				m.EvalContext = &SPFreshEvalContext{}
			}
			if err := m.EvalContext.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSpfresh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpfresh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SPFreshEvalContext) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpfresh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SPFreshEvalContext: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SPFreshEvalContext: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeZoneName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeZoneName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeZoneOffset", wireType)
			}
			m.TimeZoneOffset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeZoneOffset |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxWarningCount", wireType)
			}
			m.MaxWarningCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxWarningCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DivPrecisionIncrement", wireType)
			}
			m.DivPrecisionIncrement = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DivPrecisionIncrement |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TruncateMode", wireType)
			}
			m.TruncateMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TruncateMode |= SPFreshTruncateMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OverflowAsWarning", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OverflowAsWarning = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoZeroInDate", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NoZeroInDate = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoZeroDate", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NoZeroDate = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowInvalidDates", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowInvalidDates = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StrictSqlMode", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StrictSqlMode = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreZeroInDate", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IgnoreZeroInDate = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DividedByZeroAsWarning", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DividedByZeroAsWarning = bool(v != 0)
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorForDivisionByZero", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ErrorForDivisionByZero = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipSpfresh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpfresh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SPFreshFilterExprColumn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpfresh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SPFreshFilterExprColumn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SPFreshFilterExprColumn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ColumnId", wireType)
			}
			m.ColumnId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ColumnId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			m.Source = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Source |= SPFreshFilterExprColumnSource(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FieldType == nil {
				m.FieldType = &FieldType{}
			}
			if err := m.FieldType.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSpfresh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpfresh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SPFreshSearchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpfresh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SPFreshSearchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SPFreshSearchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rows = append(m.Rows, &SPFreshSearchRow{})
			if err := m.Rows[len(m.Rows)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stats == nil {
				m.Stats = &SPFreshSearchStats{}
			}
			if err := m.Stats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Warnings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Warnings = append(m.Warnings, &Error{})
			if err := m.Warnings[len(m.Warnings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WarningCount", wireType)
			}
			m.WarningCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WarningCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSpfresh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpfresh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SPFreshSearchRow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpfresh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SPFreshSearchRow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SPFreshSearchRow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HandleBytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HandleBytes = append(m.HandleBytes[:0], dAtA[iNdEx:postIndex]...)
			if m.HandleBytes == nil {
				m.HandleBytes = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distance", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Distance = float32(math.Float32frombits(v))
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ColumnValues", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSpfresh
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSpfresh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ColumnValues = append(m.ColumnValues, make([]byte, postIndex-iNdEx))
			copy(m.ColumnValues[len(m.ColumnValues)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSpfresh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpfresh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SPFreshSearchStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpfresh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SPFreshSearchStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SPFreshSearchStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartitionsScanned", wireType)
			}
			m.PartitionsScanned = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PartitionsScanned |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VectorsScanned", wireType)
			}
			m.VectorsScanned = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VectorsScanned |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableLookupKeys", wireType)
			}
			m.TableLookupKeys = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableLookupKeys |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableLookupBytes", wireType)
			}
			m.TableLookupBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableLookupBytes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PermitMicros", wireType)
			}
			m.PermitMicros = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PermitMicros |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigMicros", wireType)
			}
			m.ConfigMicros = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConfigMicros |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexOpenMicros", wireType)
			}
			m.IndexOpenMicros = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexOpenMicros |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SearchMicros", wireType)
			}
			m.SearchMicros = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SearchMicros |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableLookupMicros", wireType)
			}
			m.TableLookupMicros = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableLookupMicros |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TikvClientRpcCount", wireType)
			}
			m.TikvClientRpcCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TikvClientRpcCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TikvClientRpcMicros", wireType)
			}
			m.TikvClientRpcMicros = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TikvClientRpcMicros |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReadOnly = bool(v != 0)
		case 13:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field OversampleFactor", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.OversampleFactor = float64(math.Float64frombits(v))
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartitionCacheHits", wireType)
			}
			m.PartitionCacheHits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PartitionCacheHits |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartitionCacheMisses", wireType)
			}
			m.PartitionCacheMisses = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PartitionCacheMisses |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSpfresh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpfresh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSpfresh(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSpfresh
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSpfresh
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSpfresh
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSpfresh
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSpfresh
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSpfresh        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSpfresh          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSpfresh = fmt.Errorf("proto: unexpected end of group")
)
